---
- name: Ensure spring-configuration directory exists
  file:
    path: /usr/src/cas-overlay/src/main/webapp/WEB-INF/spring-configuration
    state: directory
    recurse: yes
- name: Use local pom.xml
  template:
    src: pom.xml.j2
    dest: /usr/src/cas-overlay/pom.xml
- name: Use local propertyFileConfigurer.xml
  template:
    src: propertyFileConfigurer.xml.j2
    dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/spring-configuration/propertyFileConfigurer.xml
- name: Use local deployerConfigContext.xml
  template:
    src: deployerConfigContext.xml.j2
    dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/deployerConfigContext.xml
- name: Build CAS
  #command: "mvn -B -e -l /vagrant/maven_error clean package install"
  shell: >
    bash -c "export JAVA_HOME=/usr/lib/jvm/java && ./mvnw clean package"
  args:
    chdir: /usr/src/cas-overlay
    #creates: /usr/src/cas-4.2.4/target/cas.war 
