---

- name: Remove Service Declaration overlay directory
  file:
    path: /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/services
    state: absent

- name: Ensure overlay directories exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - /usr/src/cas-overlay/src/main/webapp/WEB-INF/spring-configuration
    - /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/services
    - /usr/src/cas-overlay/src/main/webapp/WEB-INF/view/jsp/default/ui/includes
    - /usr/src/cas-overlay/src/main/webapp/css
    - /usr/src/cas-overlay/src/main/webapp/images
    - /usr/src/cas-overlay/src/main/webapp/js

- name: Use local templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: pom.xml.j2
      dest: /usr/src/cas-overlay/pom.xml
    - src: propertyFileConfigurer.xml.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/spring-configuration/propertyFileConfigurer.xml
    - src: deployerConfigContext.xml.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/deployerConfigContext.xml
    - src: messages.properties.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/messages.properties
    - src: casLoginView.jsp.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/view/jsp/default/ui/casLoginView.jsp

- name: Create Service Declarations
  template:
    src: ServiceDeclaration.json.j2
    dest: "/usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/services/{{ item.file }}-{{ item.id }}.json"
  with_items: cas_services

- name: Use local files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: top.jsp
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp
    - src: bottom.jsp
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/bottom.jsp
    - src: cas.css
      dest: /usr/src/cas-overlay/src/main/webapp/css/cas.css
    - src: logo.png
      dest: /usr/src/cas-overlay/src/main/webapp/images/logo.png
    - src: cas.js
      dest: /usr/src/cas-overlay/src/main/webapp/js/cas.js

- name: Build CAS
  shell: >
    bash -c "export JAVA_HOME=/usr/lib/jvm/java && ./mvnw clean package"
  args:
    chdir: /usr/src/cas-overlay

- name: Build JSON Web Key Generator
  shell: >
    bash -c "export JAVA_HOME=/usr/lib/jvm/java && mvn clean package"
  args:
    chdir: /usr/src/json-web-key-generator
    creates: /usr/src/json-web-key-generator/target/json-web-key-generator-0.3-jar-with-dependencies.jar
