---
- name: Ensure overlay directories exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - /usr/src/cas-overlay/src/main/webapp/WEB-INF/spring-configuration
    - /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/services
    - /usr/src/cas-overlay/src/main/webapp/WEB-INF/view/jsp/default/ui/includes

- name: Use local templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: pom.xml.j2
      dest: /usr/src/cas-overlay/pom.xml
    - src: propertyFileConfigurer.xml.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/spring-configuration/propertyFileConfigurer.xml
    - src: deployerConfigContext.xml.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/deployerConfigContext.xml
    - src: ServiceDeclaration.json.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/services/ServiceDeclaration.json
    - src: messages.properties.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/messages.properties

- name: Use local files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: casLoginView.jsp
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/view/jsp/default/ui/casLoginView.jsp
    - src: top.jsp
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp
    - src: bottom.jsp
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/bottom.jsp

- name: Build CAS
  shell: >
    bash -c "export JAVA_HOME=/usr/lib/jvm/java && ./mvnw clean package"
  args:
    chdir: /usr/src/cas-overlay
    creates: /usr/src/cas-overlay/target/cas.war 
