---

- name: Ensure Directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: wheel
    mode: 0775
    recurse: yes
  with_items:
    - /etc/cas/config


- name: Initialize CAS Configuration
  command: >
    ./gradlew copyCasConfiguration
  args:
    chdir: /usr/src/cas-overlay

- name: Overlay src and target directories are absent
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/src/cas-overlay/src
    - /usr/src/cas-overlay/target

- name: Overlay src directories exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/services
    - /usr/src/cas-overlay/src/main/webapp/WEB-INF/spring-configuration

- name: Configure overlay using role templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: pom.xml.j2
      dest: /usr/src/cas-overlay/pom.xml
    - src: messages.properties.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/messages.properties

- name: Create Service Declarations
  template:
    src: ServiceDeclaration.json.j2
    dest: "/usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/services/{{ item.file }}-{{ item.id }}.json"
  with_items:
    - "{{ cas_services }}"

- name: Build CAS
  command: >
    ./gradlew clean build
  args:
    chdir: /usr/src/cas-overlay
