---

- name: Ensure Directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: wheel
    mode: 0775
    recurse: yes
  with_items:
    - /etc/cas/config

- name: Build JSON Web Key Generator
  command: >
    bash -c "mvn clean package"
  args:
    chdir: /usr/src/json-web-key-generator
    creates: /usr/src/json-web-key-generator/target/json-web-key-generator-0.3-jar-with-dependencies.jar
  environment:
    JAVA_HOME: /usr/lib/jvm/java

- name: Generate cookie keys
  command: >
   java -jar json-web-key-generator-0.3-jar-with-dependencies.jar -t oct -s "{{ item.size }}" -o /etc/cas/"{{ item.name }}".json
  args:
    chdir: /usr/src/json-web-key-generator/target
    creates: "/etc/cas/{{ item.name}}.json"
  environment:
    JAVA_HOME: /usr/lib/jvm/java
  with_items:
    - name: tgc.encryption.key
      size: 256
    - name: tgc.signing.key
      size: 512

- name: Get cookie encryption key value
  shell: >
   cat /etc/cas/tgc.encryption.key.json | jq --raw-output '.k'
  register: cas_tgc_encryption_key

- name: Set encryption key value as fact
  set_fact:
    cas_tgc_encryption_key: "{{ cas_tgc_encryption_key.stdout }}"

- name: Get cookie signing key value
  shell: >
   cat /etc/cas/tgc.signing.key.json | jq --raw-output '.k'
  register: cas_tgc_signing_key

- name: Set signing key value as fact
  set_fact:
    cas_tgc_signing_key: "{{ cas_tgc_signing_key.stdout }}"

- name: Remove service declaration overlay directory
  file:
    path: /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/services
    state: absent

- name: Ensure empty service declaration overlay directory exists
  file:
    path: /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/services
    state: directory
    recurse: yes

- name: Ensure spring configuration overlay directory exists
  file:
    path: /usr/src/cas-overlay/src/main/webapp/WEB-INF/spring-configuration
    state: directory
    recurse: yes

- name: Ensure jsp ui overlay directory exists
  file:
    path: /usr/src/cas-overlay/src/main/webapp/WEB-INF/view/jsp/default/ui
    state: directory
    recurse: yes

- name: Configure overlay using role templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: pom.xml.j2
      dest: /usr/src/cas-overlay/pom.xml
    - src: messages.properties.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/messages.properties
    - src: casLoginView.jsp.j2
      dest: /usr/src/cas-overlay/src/main/webapp/WEB-INF/view/jsp/default/ui/casLoginView.jsp

- name: Create Service Declarations
  template:
    src: ServiceDeclaration.json.j2
    dest: "/usr/src/cas-overlay/src/main/webapp/WEB-INF/classes/services/{{ item.file }}-{{ item.id }}.json"
  with_items:
    - "{{ cas_services }}"

- name: Build CAS
  command: >
    ./mvnw clean package
  args:
    chdir: /usr/src/cas-overlay
  environment:
    JAVA_HOME: /usr/lib/jvm/java
