---
- name: Remove previous deployment
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /cas-overlay/cas.war
- name: Deploy war
  copy:
    remote_src: True
    src: /usr/src/cas-overlay/build/libs/cas.war
    dest: /cas-overlay/cas.war
